version: '3.8'
services:
  vib-next:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    image: vib-next-app:prod
    restart: unless-stopped
    env_file:
      - .env.production
    ports:
      - '3000:3000'
    volumes: []
