name = "vib-relay"
main = "worker.js"
account_id = "ecfba8cdc1c84a7d1adad77f04b86989"
compatibility_date = "2025-09-15"

[vars]
# REQUIRE_HMAC = "1"
# DEBUG_RETURN_OTP = "1"
# DEMO_STATIC_OTP = "1"
# DEV_ALLOW_ENVINFO = "1"

[[kv_namespaces]]
binding = "APP_KV"
id = "__PROD_APP_KV_ID__"

[env.preview]
[[env.preview.kv_namespaces]]
binding = "APP_KV"
id = "__PREVIEW_APP_KV_ID__"
